import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { PageTransitionProvider } from "./context/pageTransition";
import Nav from "./components/Nav";
import Curtain from "./components/Curtain";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistMono.variable} antialiased`}>
        <PageTransitionProvider enterDuration={100} exitDuration={100}>
          <div className="relative">
            <Curtain />
            <Nav />
            <main>{children}</main>
          </div>
        </PageTransitionProvider>
      </body>
    </html>
  );
}
