import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { PageTransitionProvider } from "./context/pageTransition";
import Nav from "./components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout rendered");
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistMono.variable} bg-white antialiased`}
      >
        <PageTransitionProvider enterDuration={300} exitDuration={300}>
          <div className="relative">
            <Nav />
            <div>{children}</div>
          </div>
        </PageTransitionProvider>
      </body>
    </html>
  );
}
